import { useEffect,useState } from "react";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { MapPin,RefreshCw } from "lucide-react";
type Driver={id:string;name:string;registration:string|null;lat:number|null;lng:number|null;sharing:boolean;online:boolean;updatedAt:string|null};
type Proof={id:number;orderId:number;driverName:string;recordedAt:string;lat:number|null;lng:number|null;accuracyMetres:number|null;locationStatus:string};
export default function DriverLocations(){
 const [drivers,setDrivers]=useState<Driver[]>([]),[error,setError]=useState(""),[orderId,setOrderId]=useState(""),[proofs,setProofs]=useState<Proof[]>([]);
 const load=async()=>{try{const r=await fetch("/api/dispatch/locations",{credentials:"include",cache:"no-store"});if(!r.ok)throw Error("Driver map request failed ("+r.status+")");setDrivers(await r.json());setError("")}catch(e:any){setError(e.message)}};
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>clearInterval(t)},[]);
 const active=drivers.filter(d=>d.online&&Number.isFinite(Number(d.lat))&&Number.isFinite(Number(d.lng)));
 const points=JSON.stringify(active.map(d=>({name:d.name,lat:d.lat,lng:d.lng}))).replace(/</g,"\\u003c");
 const mapDoc=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;margin:0}body{font-family:Arial}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const points=${points};const map=L.map("map").setView([55.85,-4.3],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors",maxZoom:18}).addTo(map);const markers=points.map(p=>{const m=L.marker([p.lat,p.lng]).addTo(map);m.bindTooltip(p.name);return m});if(markers.length)map.fitBounds(L.featureGroup(markers).getBounds().pad(.35),{maxZoom:14});</script></body></html>`;
 const search=async()=>{setError("");try{const r=await fetch("/api/dispatch/proofs?orderId="+encodeURIComponent(orderId),{credentials:"include"});const data=await r.json();if(!r.ok)throw Error(data.message||"Audit lookup failed");setProofs(data)}catch(e:any){setError(e.message)}};
 return <div className="p-4 md:p-6 space-y-4"><div className="flex flex-wrap justify-between gap-2 items-center"><div><h1 className="text-2xl font-semibold">Driver Locations</h1><p className="text-sm text-muted-foreground">Admin only · updates approximately every 30 seconds · shows consented, recent positions</p></div><Button variant="outline" onClick={load}><RefreshCw className="w-4 h-4 mr-2"/>Refresh</Button></div>
 <Card><CardContent className="p-3"><iframe title="Live driver locations" srcDoc={mapDoc} className="w-full h-[380px] rounded-lg border" sandbox="allow-scripts" referrerPolicy="no-referrer"/></CardContent></Card>
 <div className="grid gap-3 md:grid-cols-3">{drivers.map(d=><Card key={d.id}><CardContent className="p-4 space-y-1"><strong>{d.name}</strong><p className="text-sm">{d.registration||"No registration"}</p><p className={"text-xs "+(d.online?"text-green-700":"text-muted-foreground")}>{d.online?"Sharing location":"Offline / not sharing"}</p>{d.updatedAt&&<p className="text-xs text-muted-foreground">Last position: {new Date(d.updatedAt).toLocaleString("en-GB")}</p>}</CardContent></Card>)}</div>
 <Card><CardHeader><CardTitle>Delivery audit trail</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-muted-foreground">Look up an order to view completion records. GPS is only displayed when the driver granted permission and the reading met the accuracy threshold.</p><div className="flex gap-2"><input value={orderId} onChange={e=>setOrderId(e.target.value)} inputMode="numeric" placeholder="Internal order ID" aria-label="Order ID" className="border rounded-lg px-3 py-2 w-48 bg-background"/><Button onClick={search}>View proof</Button></div>{proofs.map(p=><div key={p.id} className="border rounded-lg p-3 text-sm"><strong>{p.driverName}</strong> — {new Date(p.recordedAt).toLocaleString("en-GB")}<p>GPS: {p.locationStatus}{p.accuracyMetres!=null?" · accuracy ±"+Math.round(p.accuracyMetres)+" m":""}</p>{p.lat!=null&&p.lng!=null&&<a className="underline" target="_blank" rel="noopener noreferrer" href={"https://www.openstreetmap.org/?mlat="+p.lat+"&mlon="+p.lng+"#map=18/"+p.lat+"/"+p.lng}>View recorded location</a>}</div>)}</CardContent></Card>
 {error&&<p className="text-sm text-red-700" role="alert">{error}</p>}</div>;
}
